# permissions for end users to view dekeris.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dekeris-viewer-role
rules:
- apiGroups:
  - games.dekeris.github.io
  resources:
  - dekeris
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - games.dekeris.github.io
  resources:
  - dekeris/status
  verbs:
  - get
