
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - games.dekeris.github.io
  resources:
  - dekeris
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - games.dekeris.github.io
  resources:
  - dekeris/finalizers
  verbs:
  - update
- apiGroups:
  - games.dekeris.github.io
  resources:
  - dekeris/status
  verbs:
  - get
  - patch
  - update
